version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: biblioteca
    environment:
      POSTGRES_DB: bibliotecadb
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
